version: "3.4"
services:
    buscaativa_db:
        image: postgres
        container_name: buscaativa_db
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: buscaativa
            POSTGRES_DB: buscaativa
    buscaativa:
        build: .
        container_name: buscaativa
        ports: 
            - 3333:3333
        volumes:
            - .:/usr/app
        depends_on:
            - buscaativa_db
    
volumes:
    pgdata: